# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\"1\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"X\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nusuario_id\x18\x03 \x01(\x03\x12\x1e\n\x05songs\x18\x04 \x03(\x0b\x32\x0f.streaming.Song\"*\n\x08UserList\x12\x1e\n\x05users\x18\x01 \x03(\x0b\x32\x0f.streaming.User\"*\n\x08SongList\x12\x1e\n\x05songs\x18\x01 \x03(\x0b\x32\x0f.streaming.Song\"6\n\x0cPlaylistList\x12&\n\tplaylists\x18\x01 \x03(\x0b\x32\x13.streaming.Playlist\"\x07\n\x05\x45mpty\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xc8\x02\n\x10StreamingService\x12\x32\n\tListUsers\x12\x10.streaming.Empty\x1a\x13.streaming.UserList\x12\x32\n\tListSongs\x12\x10.streaming.Empty\x1a\x13.streaming.SongList\x12\x44\n\x13ListPlaylistsByUser\x12\x14.streaming.IdRequest\x1a\x17.streaming.PlaylistList\x12@\n\x13ListSongsByPlaylist\x12\x14.streaming.IdRequest\x1a\x13.streaming.SongList\x12\x44\n\x13ListPlaylistsBySong\x12\x14.streaming.IdRequest\x1a\x17.streaming.PlaylistListB4\n br.unifor.streaming_musicas.grpcB\x0eStreamingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n br.unifor.streaming_musicas.grpcB\016StreamingProtoP\001'
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=77
  _globals['_SONG']._serialized_start=79
  _globals['_SONG']._serialized_end=128
  _globals['_PLAYLIST']._serialized_start=130
  _globals['_PLAYLIST']._serialized_end=218
  _globals['_USERLIST']._serialized_start=220
  _globals['_USERLIST']._serialized_end=262
  _globals['_SONGLIST']._serialized_start=264
  _globals['_SONGLIST']._serialized_end=306
  _globals['_PLAYLISTLIST']._serialized_start=308
  _globals['_PLAYLISTLIST']._serialized_end=362
  _globals['_EMPTY']._serialized_start=364
  _globals['_EMPTY']._serialized_end=371
  _globals['_IDREQUEST']._serialized_start=373
  _globals['_IDREQUEST']._serialized_end=396
  _globals['_STREAMINGSERVICE']._serialized_start=399
  _globals['_STREAMINGSERVICE']._serialized_end=727
# @@protoc_insertion_point(module_scope)
